version: '3.8'

services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: satisfacao
    ports:
      - "5432:5432"
    networks:
      - sistema-network

  mongodb:
    build: ./mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - sistema-network

  node:
    build: ./node-app
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - sistema-network
    volumes:
      - ./node-app:/app

networks:
  sistema-network:
    driver: bridge